name: Build in Cygwin
on:
  push:
    branches: [ cygwin-build ]
  pull_request:
    branches: [ cygwin-build ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cygwin setup
        uses: egor-tensin/setup-cygwin@v3
        with:
          packages: python38-devel,make,gcc,dos2unix
      - name: build & test
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U pytest
          cd D:/a/pynauty/pynauty
          echo ==============================================
          echo shell $SHELL
          which -a sh bash
          ls -ld /bin/sh /bin/bash
          ls -ld /usr/include/python3.8/*
          find /usr/include -name Python.h
          echo ==============================================
          make pynauty
          make minimal-test
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
